[package]
name = "connection-leak-detector"
authors = ["Finn Bear"]
version = "0.1.0"
edition = "2021"
license = "UNLICENSE"

[dependencies]
enum-iterator = "0.7"

[dev-dependencies]
actix-web = "4.0.0-beta.12"
actix-rt = "2"
tokio = "1"
serial_test = "0.5"